import type { GeneratedFile } from "@praxis/file-generator";

export type ProjectTemplateKind = "documentation-first" | "tauri-desktop-minimal" | "blank";

export function generateTemplateFiles(kind: ProjectTemplateKind, projectName: string): GeneratedFile[] {
  if (kind === "blank") return [];
  const base: GeneratedFile[] = [
    {
      path: "README.md",
      content: `# ${projectName}\n\nGenerated by Praxis Studio.\n`
    },
    {
      path: "docs/PRODUCT_SPEC.md",
      content: `# Product Spec\n\nProject: ${projectName}\n`
    },
    {
      path: "docs/ARCHITECTURE.md",
      content: `# Architecture\n\nArchitecture candidates will be refined through the Development Graph.\n`
    },
    {
      path: "docs/ROADMAP.md",
      content: "# Roadmap\n\n- Confirm requirements\n- Confirm architecture\n- Generate controlled coding tasks\n"
    }
  ];
  if (kind === "tauri-desktop-minimal") {
    base.push({
      path: "package.json",
      content: JSON.stringify(
        {
          name: projectName.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
          version: "0.1.0",
          private: true,
          type: "module",
          scripts: { dev: "vite", build: "vite build" }
        },
        null,
        2
      )
    });
  }
  return base;
}
